# Generated by Django 4.1 on 2022-11-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='traveller')),
                ('verification', models.FileField(blank=True, default='default.jpg', null=True, upload_to='pdf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Houseown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='Houseownimg')),
                ('verification', models.FileField(blank=True, default='default.jpg', null=True, upload_to='ownpdfs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('facility', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='House')),
                ('location', models.CharField(max_length=200)),
                ('space', models.IntegerField(max_length=20)),
                ('houseown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.houseown')),
            ],
        ),
        migrations.CreateModel(
            name='Bookedhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.traveller')),
            ],
        ),
    ]
