# Generated by Django 4.1 on 2022-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_houseown_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='contact_no',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
