# Generated by Django 4.1 on 2022-11-15 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedhouse',
            name='end_date',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
        ),
        migrations.AlterField(
            model_name='bookedhouse',
            name='start_date',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
        ),
    ]
