# Generated by Django 4.1 on 2022-11-16 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedhouse',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 19)),
        ),
        migrations.AlterField(
            model_name='bookedhouse',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 10, 19)),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
