# Generated by Django 4.1 on 2022-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_comment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
    ]
