# Generated by Django 4.1 on 2022-11-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
